[project]
name = "TurningPointUSAODU"
version = "0.1.0"
description = "This is the website for TPUSA ODU Chapter"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.6",
]

[dependency-groups]
dev = [
    "dotenv>=0.9.9",
]
